// Generated by CoffeeScript 1.10.0

/* Radius1 sets up "global" variables.  It must be the first .js to be executed.
 */

(function() {
  var Radius, initAllBoxes;

  window.Radius = {};

  Radius = window.Radius;

  jQuery(function() {
    window.Radius.PrototypesOnReady();
    initAllBoxes();
    window.Radius.ProgrammingPaneOnReady();

  });

  initAllBoxes = function() {
    var startBlock;
    Radius.TheBlockList = new Radius.BlockList();
    startBlock = new Radius.Block(new Radius.Box("Start", "ProgrammingPane").setPos(20, 20));
    return Radius.TheBlockList.addBlock(startBlock);
  };

}).call(this);
