// Generated by CoffeeScript 1.10.0
(function() {
  var Radius;

  Radius = window.Radius;

  Radius.Token = (function() {
    Token.String = "ST";

    Token.Number = "NU";

    Token.Word = "WD";

    Token.Symbol = "SY";

    Token.Operator = "OP";

    Token.Function = "FN";

    Token.Label = "LB";

    Token.Counter = "CT";

    Token.Array = "[]";

    Token.Object = "OB";

    Token.LVal = "LV";

    Token.RVal = "RV";

    Token.Command = "CM";

    Token.NoVal = "??";

    Token.Bool = "BL";

    Token.Eject = "!!";

    function Token(type, text, id, whichParm, start, length) {
      var sn;
      this.type = type;
      this.text = text;
      this.id = id != null ? id : 'none';
      this.whichParm = whichParm != null ? whichParm : 0;
      this.start = start != null ? start : 0;
      this.length = length != null ? length : 0;
      this.val = this.text;
      this.error = false;
      this.sym = "";
      this.depth = 0;
      this.serial = 0;
      if (this.type === Token.Word || this.type === Token.Operator) {
        this.val = this.text.toLowerCase();
      }
      if (this.type === Token.Counter) {
        this.val = +this.text;
      }
      if (this.type === Token.Number) {
        sn = SchemeNumber.fn["string->number"]("#e" + this.text);
        if (sn) {
          this.val = sn;
        } else {
          console.log("Token ctor: this token couldn't be handled by SchemeNumber:", this.text);
          this.val = null;
          this.error = true;
        }
      }
      if (this.type === Token.Symbol) {
        this.sym = this.text;
      }
    }

    return Token;

  })();

}).call(this);
